[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "mido>=1.3.3",
    "music21>=9.7.0",
    "numpy>=1.26.4",
    "werkzeug>=3.1.3",
]
